// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package markdown.actions;

import org.markdown4j.Markdown4jProcessor;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class ProcessMarkdownJava extends CustomJavaAction<String>
{
	private String mdText;

	public ProcessMarkdownJava(IContext context, String mdText)
	{
		super(context);
		this.mdText = mdText;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String html = new Markdown4jProcessor().process(mdText);
		return html;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ProcessMarkdownJava";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
